### ISSUE TITLE
Question about group by clause in DataFrames

### ISSUE THREAD

**Issue by ingomueller-net** [RumbleDB/rumble#652]
Currently, `FlworDataFrameUtils.getGroupbyProjectSQL` contains the following [lines](https://github.com/RumbleDB/rumble/blob/fff8f70238b864105f743f0f8963f8fed0536665/src/main/java/org/rumbledb/runtime/flwor/FlworDataFrameUtils.java#L307):

```java
if (groupingKey) {
    queryColumnString.append("array(");
    queryColumnString.append("first(`");
} else {
    queryColumnString.append("collect_list(`");
}
```

If I am not completely wrong, this means that the grouping keys are aggregated with the `first` function and the result is put into an array. Both are weird: First, the grouping keys aren't groups; there is only one of them, so why "aggregate" them? `first` on one value will just return that value. Second, since `first` always returns one value, why put that into an array?

Since everything works, this is problably not a bug. I have tried commenting out these two lines and things still seem to work. Overall, I don't really understand what is happening. If these two function calls are not necessary (as I would guess), I think it would be better to remove them: they are confusing at least and may have a negative performance impact at worst.

**Comment by ingomueller-net** [comment]
Nevermind. The code is fine; I understand what it is doing now.

**Comment by CanBerker** [comment]
@ingomueller-net thanks a lot for looking into this and I'm glad to hear that you were able to decipher what the code was trying to accomplish :) 

I took this issue as an opportunity to refactor this bit and hopefully make it cleaner.

**Comment by ghislainfourny** [comment]
> First, the grouping keys aren't groups; there is only one of them, so why "aggregate" them? `first` on one value will just return that value. 

This is because the "SQL grouping" is done on extra (transient) columns with native DataFrame types, not on the original item columns. As a consequence, the original (equivalent, but not always equal!) atomic items are in an array after the grouping because from SQL's perspective on the low level, they are not grouping keys. We must thus take the first one.

There are already optimizations plans to improve this when the type of the keys is known statically, then SQL will group directly on the original column and it will be faster.

> Second, since `first` always returns one value, why put that into an array?

I think this is only because later in the code, both grouping and non-grouping fields are handled with the same code that expects them all in arrays.

@CanBerker many thanks for the cleanup, it helps. I will take a look.

**Comment by ingomueller-net** [comment]
Thanks for the clarification! That's what the paper also says :P
