### ISSUE TITLE
Multiplicative Operation - Cosmetic Improvement

### ISSUE THREAD

**Issue by CanBerker** [RumbleDB/rumble#73]
These results present a noticable number of zeroes in the decimal part during multiplicative operation and use of bigdecimals in such operations

1e0 * 2.0       -> 2.00
1.0000 * 2e0 -> 2.00000
1.0 * 2e4      -> 20000.00

4 div 2         -> 2
4 div 2.0       -> 2.0000000000
4 div 2e0       -> 2.0
4.0 div 2e0     -> 2.0000000000
4.0 div 2       -> 2.0000000000
4e0 div 2       -> 2.0
4e0 div 2.0     -> 2.0000000000

**Comment by ghislainfourny** [comment]
@AndreaRinaldi1 is it what you have fixed, recently?

**Comment by AndreaRinaldi1** [comment]
Yes exactly. I fixed this recently. All the examples above are returning 2 now, without trailing zeros. 

There is just quite specific cases where the stripping of trailing zeros cannot happen, because we are dealing with doubles, like: 
`(1 + 3.14 + 10e1) * 0.1` that gives `10.414000000000001` instead of `10.414` but we already agreed on keeping this behavior instead of casting the result to BigDecimal, stripping zeros and casting back to double. 

If you agree, I can close the issue. @ghislainfourny
