### ISSUE TITLE
Insert-before works weird on arrays

### ISSUE THREAD

**Issue by mstevan** [RumbleDB/rumble#873]
@mstevan
test-set: array/head.xml 
test-cases: everything but more specific array-head-603

@team
It seems that insert-before on array, does what insert-before on sequence would do and looks at array as sequence of one element. But still the output is quite weird and not according to array:insert-before in xml expectations

**Input:**
insert-before(["a", "b", "c", "d"], 3, ["x", "y"])

**Output:**
[ "a", "b", "c", "d" ]
[ "x", "y" ]

**Expected output:**
["a", "b", ["x", "y"], "c", "d"]

**Comment by ghislainfourny** [comment]
Thanks for the feedback!

The behavior is correct. insert-before works on sequences not array, because that's fn:insert-before. We do not support (yet) array:insert-before but it's nice to have it on the radar.

To work on an array you need to unbox and rebox.

For now the workaround is:

[ insert-before(["a", "b", "c", "d"][], 3, ["x", "y"]) ]

**Comment by mstevan** [comment]
For now we will exclude this test-set until feature is implemented (Category 2: Fails, as expected since it is not supported yet)
