### ISSUE TITLE
Null pointer exception when an ordering criterion is always the empty sequence

### ISSUE THREAD

**Issue by mmilanta** [RumbleDB/rumble#906]
It might be an invalid query, I am not very confident with Jsoniq
```
for $i in json-file("confusion-2014-03-02.json")
       where $i.target eq $i.guess
       order by $i.lenguage ascending, $i.country ascending, $i.date ascending
       count $c
       where $c <= 5
return $i
```
The error was:
```
[ERROR] An error has occurred: null
We should investigate this 🙈. Please contact us or file an issue on GitHub with your query. 
Link: https://github.com/RumbleDB/rumble/issues
```

**Comment by ghislainfourny** [comment]
Thank you for your bug report! Indeed that's a bug, and a fix is under way.

However, it can help you to know that your query has a typo: lenguage instead of language. It resulted in the empty sequence (which is where the bug was).

If you use language, it should work again even with Rumble 1.10.0.

I hope it helps!

**Comment by ghislainfourny** [comment]
This is now fixed in the master and will make it into the next release.

If you feel adventurous, you can try to compile the master and confirm that it works for you (the first ordering criterion will just be ignored as it is constantly the empty sequence because of the typo, but no error should be returned any more).

**Comment by ghislainfourny** [comment]
Another remark: A master student is currently implementing the static typing feature for Rumble. With this new feature in place, Rumble will, at some point, detect such cases and return an error warning you about your typo.

**Comment by mmilanta** [comment]
Thanks for the feedback,
I'll definitely try to compile the master; however, for now, I have
incountered some issues with maven.
Many Thanks
Marco

**Comment by ghislainfourny** [comment]
Thanks! Rumble is usually released every two months, so it will make it to the next release (1.11.0). We are currently pushing 1.10.0 into Maven in case you need the latest official release.

**Comment by ghislainfourny** [comment]
@mmilanta the fix is available in the current releases. Do you agree if we close this issue?
